### ISSUE TITLE
Override compiler options in sw.cpp

### ISSUE THREAD

**Issue by ollydev** [SoftwareNetwork/sw#52]
Sorry for being a pain, but is there any way to override options that are added in the projects sw.cpp from the command line?
For example, I don't want this `libtesseract.CompileOptions.push_back("-arch:AVX2");`

Or is it designed to manually change sw.cpp if you need to change options?

**Comment by egorpugin** [comment]
> but is there any way to override options that are added in the projects sw.cpp from the command line?

No, option passing to deep deps is in TODO list.
Currently the only way (IIRC) is to comment it.

Actually, sw has a way to do this, but I did not investigate UX questions - cli options etc.
In other words, how user will pass it to tesseract library.

**Comment by egorpugin** [comment]
> Sorry for being a pain

It's ok. :) More users' requests - more features.

**Comment by ollydev** [comment]
Just a random thought, not too familar with the project so this might not make sense

`-buildoptions TESSERACT_USE_AVX2`

```c++
if (libtesseract.getBuildSettings().hasOption("TESSERACT_USE_AVX2")) {
    libtesseract.CompileOptions.push_back("-arch:AVX2");
}
```

**Comment by egorpugin** [comment]
Yes. The second part (code) is very correct and even exists in sw (and works and even more features there).
https://github.com/SoftwareNetwork/sw/blob/master/src/sw/driver/dependency.h#L40

The first part is what I called UX - they way how you pass that option through whole sw to target package (org....libtesseract in your case). It is not done yet. It is one of the core features of sw that is not implemented yet (research part is almost done there).

**Comment by egorpugin** [comment]
One more thing.

What happens under the hood if you override something?
Sw will create (compile, build) separate version of binaries of changed package and all dependent packages in the graph.
So, when you enable default avx2 flag (on or off), you'll re-use binary packages previously built.
This is very cool property of sw and it is already there too.

(I'm not talking about disk space, because binaries later won't be built on your pc and will be downloaded like in usual package managers - securily of course and with check of gpg or any other signature. So no object files in this case. And when you explicitly ask for binary package with different options and there's no such binary on the web - package will be build on your system.)
