### ISSUE TITLE
CMAKE Error: x86 only

### ISSUE THREAD

**Issue by rweldin** [SoftwareNetwork/sw#57]
When attempting to generate a Visual Studio solution file with CMAKE for Leptonica or Tesseract with the command below an exception is thrown. Both Leptonica and Tesseract generate a solution file and build fine when targeting x64. If you need any other information please let me know. Thanks!

cmake -G "Visual Studio 15 2017" -DBUILD_SHARED_LIBS=1 -DSW_BUILD_SHARED_LIBS=0 ..

Exception in file D:/dev/cppan2/client2/src/sw/driver/module.cpp:120, function operator (): error in module (C:/Users/AdminWeldin/.sw/storage/tmp/cfg/102948/loc.sw.self.e0f40a-0.0.28.dll): Exception in file C:/Users/AdminWeldin/.sw/storage/pkg/f5/fe/083c/src/sdir/sw.cpp:115, function build: no type: 0, 0
sw command: C:/.sw/sw.exe -static -platform x86 -compiler msvc-19.16 -d E:/src/leptonica/bin/.sw/cmake -config d,msr,rwdi,r integrate -cmake-deps E:/src/leptonica/bin/.sw/cmake/sw.txt -cmake-file-version 4
CMake Error at C:/Users/AdminWeldin/.sw/storage/etc/sw/static/SWConfig.cmake:232 (message):
  sw: non-zero exit code: 1
Call Stack (most recent call first):
  CMakeLists.txt:120 (sw_execute)

**Information:**
E:\src\leptonica\bin>sw --version
sw.client.sw version 1.0.0
git revision 1fe6d9946df29af1295194e8b5712abb2967ceb3
assembled on
26.09.2020 22:13:22 UTC
26.09.2020 17:13:22 Central Daylight Time

Windows 10 x64

**Comment by egorpugin** [comment]
Confirmed, thank you.

**Comment by egorpugin** [comment]
Actually looks like a regression. I fixed this some time ago, then changed a number once again during refactoring.
Please, check attached file. It works for me.
I won't be updating website or (`sw --self-upgrade`) binaries with this old client, because I'm working on new changes in master.
The fix - https://github.com/SoftwareNetwork/sw/commit/864f337445df81869029bbc336b43d72f01c94c0

[sw.client.sw-1.0.0.exe.zip](https://github.com/SoftwareNetwork/sw/files/5541217/sw.client.sw-1.0.0.exe.zip)

**Comment by egorpugin** [comment]
You may need to clean `C:/Users/AdminWeldin/.sw/storage/etc/sw/checks` dir first.

**Comment by rweldin** [comment]
Works great. Thank you!
