### ISSUE TITLE
Bootstrap Builds

### ISSUE THREAD

**Issue by tay10r** [SoftwareNetwork/sw#6]
It would be nice to be able to build `sw` without downloading a binary.
I suggest having a Makefile generator script, that can be updated every so often, for users that don't already have a binary on their system.

I did this once, at [here](https://github.com/tay10r/cmEngine/blob/master/Scripts/update-makefile.sh). The header file dependencies are detected by GCC. I could draft a PR for a similar script `sw`, just as long as the build is trivial enough.

**Comment by egorpugin** [comment]
Hi!

Yes, sure.
Just removed "bootstrap" way of building with cppan (sw v1) from readme today.
https://github.com/SoftwareNetwork/sw/commit/a1485d5de00a12118443957b8b83e937cbe48377
(And cppan may be build with cmake. Full chain was `make` -> `cmake` -> `cppan` -> `sw`.)

SW already has makefile generator as well as ninja one
https://github.com/SoftwareNetwork/sw/blob/master/src/driver/cpp/generator/generator.cpp#L2354
https://github.com/SoftwareNetwork/sw/blob/master/src/driver/cpp/generator/generator.h#L20
(implementations may be just a little a bit outdated - not sure 100%)

But here comes interesting question, because sw needs its dependencies downloaded from the network storage. I thought about writing simple script or better implementing it also as part of makefile.
Last step would be running non-sw configure steps (configure files, perform checks etc.).
All this is not so trivial.

Instead it is possible to keep minimal bootstrapped storage somewhere on the web which will be downloaded by bootstrap makefile, unpacked and then participate in fresh build.

If you'd like to contribute, I appreciate.
Otherwise this item is not on top of todo currently, sorry.

**Comment by tay10r** [comment]
@egorpugin that's totally fine, I'm willing to patch. I'll read more into it in a shortly.

**Comment by egorpugin** [comment]
Also this features is needed when porting, for example, to other linux distros.
For example, I've built linux sw on ubuntu 18.04 and cannot run it on 16.04 because of older libc.

I implemented such bootstrap procedure for cppan & cmake some time ago.

**Comment by egorpugin** [comment]
I have some theoretical progress on this.
But still it's for later time.

**Comment by tay10r** [comment]
Awesome! I'll be waiting to see what comes of it

**Comment by egorpugin** [comment]
Added in https://github.com/SoftwareNetwork/sw/commit/994bb80532b8282c5970280e34cbd7b976511958

To provide a bootstrap build for you, please, provide your OS & ver.
